### ISSUE TITLE
CPU usage spikes hourly in idle system with over 2000 devices (resource-aggregator)

### ISSUE THREAD

**Issue by rlopinfn** [plgd-dev/hub#1084]
### Description
When running plgd with 2800 onboarded devices, we noticed CPU usage spikes occurring hourly while system is in idle state.

### How can it be reproduced?
1. Have system running with 2800 devices onboarded.
2. Monitor plgd host machine CPU usage.

![resource-aggr_spikes](https://github.com/plgd-dev/hub/assets/93923940/2058afe3-05a6-4a7a-9fef-0040e260fc19)

### Environment
- plgd-dev/hub/bundle:2.12.1
- Deployment option: ( `helm` )

**Comment by jkralik** [comment]
Hi @rlopinfn. 
Could you please provide the configuration?
What is configured for the environment variable MOCK_OAUTH_SERVER_ACCESS_TOKEN_LIFETIME? If it is set to 1 hour, then this behavior is expected because devices refresh their tokens.

**Comment by jkralik** [comment]
@rlopinfn Fixed in the release https://github.com/plgd-dev/hub/releases/tag/v2.13.0 .
