### ISSUE TITLE
Enable observability by using OpenTelemetry

### ISSUE THREAD

**Issue by ondrejtomcik** [plgd-dev/hub#241]
### What is the purpose of the feature?
As we need to solve availability and performance quickly, the observability framework has to be integrated into plgd cloud. Commands and events tracing, have more insights into delays, blocking chains, bottlenecks is crucial.

### What specific challenge does this feature solve?
Understand the behavior of the system better under the load.

### What alternatives did I consider?
None

**Comment by jkralik** [comment]
Implemented in v2.4.1.
