### ISSUE TITLE
problem receiving notifications by GRPC

### ISSUE THREAD

**Issue by InfiRR** [plgd-dev/hub#270]
Hi,

Could you please advise if there are changes from release v2next-77de0a1 ( itself this version doesn't even let connection for GRPC as far as I could test it )

v2next-d387ac2 - does not trigger notifications automatically on empty startup
v2next-77de0a1 - does not connect to grpc 
v2next-b88a2ca - worked

behaviour:
1)start a PLGD bundle from scratch.
2)launch secure devices
3)launch a GRPCclient (not using the certificate). Create a subscription for  Online device status change
4)onboard devices using the SDK provided by the team

expected: online notification is caught by the subscription created ( tested up to v2next-b88a2ca with success)

observed: if no device existed before online notification is not triggered from v2next-d387ac2 up to latest. If the GRPC client subscription is launched after a device was onboarded/offboarded it will correctly receive all notifications

**Comment by ondrejtomcik** [comment]
Dear @InfiRR 

Sorry for the late feedback.
Could you please try to reproduce this issue with image plgd/bundle:v2next-0855651 ?
This version contains fix dropping messages from NATS issue. It might be related to the issue you're describing here.

**Comment by InfiRR** [comment]
Hi,

Using latest release yesterday as v2-next but should be the same as v2next-ac7eecb.

Same procedure. 
-> start PLGD bundle
-> start 5 emulators secured with the certificate from PLGD
-> start onboard app & consumer app ( consumer app registers to online, unregistered and offline and receives empty device list in each state as expected)
-> onboard device/s ( it doesn't matter if it is one or more)
-> consumer app was expected to receive new online event ( or any other ).

if the devices are onboarded before the consumer app is started then all works ok.

for the failed scenario this can be seen in grpc-gateway.log. The same type of log's are not created on the second attempt after successful onboard of devices. ( on the bottom)

Please advise if this is enough to evaluate the issue.

{"level":"error","ts":1622183143.963905,"caller":"log/log.go:117","msg":"rpc error: code = NotFound desc = cannot receive device: rpc error: code = NotFound desc = not found","stacktrace":"github.com/plgd-dev/cloud/pkg/log.Errorf\n\t/go/src/github.com/plgd-dev/cloud/pkg/log/log.go:117\ngithub.com/plgd-dev/cloud/pkg/log.LogAndReturnError\n\t/go/src/github.com/plgd-dev/cloud/pkg/log/logAndReturnError.go:21\ngithub.com/plgd-dev/cloud/grpc-gateway/service.(*RequestHandler).GetDevices\n\t/go/src/github.com/plgd-dev/cloud/grpc-gateway/service/getDevices.go:24\ngithub.com/plgd-dev/cloud/grpc-gateway/pb._GrpcGateway_GetDevices_Handler\n\t/go/src/github.com/plgd-dev/cloud/grpc-gateway/pb/service_grpc.pb.go:329\ngithub.com/plgd-dev/cloud/pkg/net/grpc.StreamServerInterceptor.func1\n\t/go/src/github.com/plgd-dev/cloud/pkg/net/grpc/interceptor.go:29\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1471\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1544\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:878"}
{"level":"error","ts":1622183204.00059,"caller":"log/log.go:117","msg":"rpc error: code = Unavailable desc = cannot receive events: rpc error: code = Unavailable desc = transport is closing","stacktrace":"github.com/plgd-dev/cloud/pkg/log.Errorf\n\t/go/src/github.com/plgd-dev/cloud/pkg/log/log.go:117\ngithub.com/plgd-dev/cloud/pkg/log.LogAndReturnError\n\t/go/src/github.com/plgd-dev/cloud/pkg/log/logAndReturnError.go:21\ngithub.com/plgd-dev/cloud/grpc-gateway/service.(*RequestHandler).SubscribeForEvents\n\t/go/src/github.com/plgd-dev/cloud/grpc-gateway/service/grpcApi.go:162\ngithub.com/plgd-dev/cloud/grpc-gateway/pb._GrpcGateway_SubscribeForEvents_Handler\n\t/go/src/github.com/plgd-dev/cloud/grpc-gateway/pb/service_grpc.pb.go:424\ngithub.com/plgd-dev/cloud/pkg/net/grpc.StreamServerInterceptor.func1\n\t/go/src/github.com/plgd-dev/cloud/pkg/net/grpc/interceptor.go:29\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1471\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1544\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:878"}

**Comment by jkralik** [comment]
@InfiRR How long you do you wait for events ? RD pulling devices from authorization server and it driven by https://github.com/plgd-dev/cloud/blob/ac7eecb66336fbe541bedaa8437592d679acc26f/resource-directory/config.yaml#L58
So by default it is 1 minute. Do you receive event after one minute ?

**Comment by InfiRR** [comment]
no, it's not dependent on elapsed time.

**Comment by jkralik** [comment]
@InfiRR I'm able replicate issue so I will fix it and cover by test case. I was not able replicate issue because I had `cacheExpiration` configured to 1s and `PullFrequency` to 500ms.

**Comment by jkralik** [comment]
@InfiRR  So the issue was that grpc servers used default configuration for [enforcementPolicy](https://github.com/grpc/grpc-go/blob/v1.38.0/keepalive/keepalive.go#L77) but our internal grpc clients violated it so servers closed connections. Could you try it with image `plgd/bundle:fixedIssue270` ? The online notification onlines comes in cca 1min.

**Comment by InfiRR** [comment]
hi, yes, I have tested in two different projects and it is now receiving the notifications as intended using the provided image.

Will this be merged for V2 in the future?

**Comment by ondrejtomcik** [comment]
I will review PR from Jozef tomorrow and merge it.
