### ISSUE TITLE
http-gateway websocket seems to have writing message issue.

### ISSUE THREAD

**Issue by Trishia** [plgd-dev/hub#345]
Below log is http-gateway log when I opened http-gateway web UI running on the my local PC. And also things menu does not show anything on the page. 

I used latest commit https://github.com/plgd-dev/cloud/commit/4604d315426e542bfbb60f9f4721b0e5add608fa you did commit yesterday. 

Should I avoid to run  plgd cloud on local PC ? or Other problem ? 
Could you look into this problem @jkralik ? 
```
  |   | 2021-07-20 23:36:36 | time="2021-07-20T14:36:36Z" level=warning msg="[read] error writing message to upstream http server: io: read/write on closed pipe"
-- | -- | -- | --
  |   | 2021-07-20 23:36:36 |  
  |   | 2021-07-20 23:36:36 |  
  |   | 2021-07-20 23:36:36 | X-Scheme: https
  |   | 2021-07-20 23:36:36 | X-Request-Id: 3bef749e96be5efc07f39914ffe6d60a
  |   | 2021-07-20 23:36:36 | X-Real-Ip: 192.168.65.6
  |   | 2021-07-20 23:36:36 | X-Forwarded-Proto: https
  |   | 2021-07-20 23:36:36 | X-Forwarded-Port: 443
  |   | 2021-07-20 23:36:36 | X-Forwarded-Host: www.ocfcloud.com
  |   | 2021-07-20 23:36:36 | X-Forwarded-For: 192.168.65.6
  |   | 2021-07-20 23:36:36 | User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
  |   | 2021-07-20 23:36:36 | Upgrade: websocket
  |   | 2021-07-20 23:36:36 | Sec-Websocket-Version: 13
  |   | 2021-07-20 23:36:36 | Sec-Websocket-Key: 1pFXTEEaBYPdqib7fF+/AQ==
  |   | 2021-07-20 23:36:36 | Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
  |   | 2021-07-20 23:36:36 | Pragma: no-cache
  |   | 2021-07-20 23:36:36 | Origin: https://www.ocfcloud.com
  |   | 2021-07-20 23:36:36 | Cookie: _legacy_auth0.is.authenticated=true; auth0.is.authenticated=true
  |   | 2021-07-20 23:36:36 | Connection: upgrade
  |   | 2021-07-20 23:36:36 | Cache-Control: no-cache
  |   | 2021-07-20 23:36:36 | Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
  |   | 2021-07-20 23:36:36 | Accept-Encoding: gzip, deflate, br
  |   | 2021-07-20 23:36:36 | Host: www.ocfcloud.com
  |   | 2021-07-20 23:36:36 | 2021-07-20T14:36:36.509Z	INFO	log/log.go:107	Request: GET /api/v1/ws/devices HTTP/1.1
```

**Comment by jkralik** [comment]
Yes, We known - we are porting UI to the new API of http-gateway ( added streaming feature via HTTP and all grpc-gateway calls). @ondrejtomcik will provide a new swagger file and in this PR https://github.com/plgd-dev/cloud/pull/343 it's UI - we need to fix one issue with http-streaming and after that, we will merge it.

**Comment by ondrejtomcik** [comment]
Swagger file is part of the v2 branch.

**Comment by Trishia** [comment]
@jkralik @ondrejtomcik 
Thank you for your kind description. 
I will test again after merging PR #343 and then report you.

**Comment by ondrejtomcik** [comment]
@Trishia is this issue still valid?

**Comment by Trishia** [comment]
@ondrejtomcik 
This issue was clear in commit https://github.com/plgd-dev/cloud/commit/0f2c187c08b0a899d7be88c05be8a9018a676508. So I close this issue.

**Comment by Trishia** [comment]
@jkralik 
New error has happened in http-gateway websocket in the latest commit e019708. 
This issue is never found in previous commit 0f2c187c08b0a899d7be88c05be8a9018a676508 that I used to test. 

See below logs: 
```
2021-08-23T08:42:57.216Z        INFO    log/log.go:113  Request: GET /api/v1/ws/events HTTP/1.1
Host: http-gateway:9086
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive, Upgrade
Cookie: io=XY_8bvT7FFaQRUh8AAB6; _legacy_auth0.is.authenticated=true; auth0.is.authenticated=true
Origin: https://www.ttaocfcloud.org
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: khqNNdK5JSCptTXW0dJOfw==
Sec-Websocket-Protocol: Bearer, eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImxfcUtMNlE3djFRNTNyZ3dSSFN1aiJ9.eyJpc3MiOiJodHRwczovL3R0YW9jZi51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDQ0MzAyMzI5NjAyMzA1ODY1OTUiLCJhdWQiOlsiaHR0cHM6Ly93d3cudHRhb2NmY2xvdWQub3JnIiwiaHR0cHM6Ly90dGFvY2YudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYyOTcwODE3MCwiZXhwIjoxNjI5Nzk0NTcwLCJhenAiOiJLaU00Wm5wMHpSZnRKenVvTFBZNTJoQ2dSWkVjSDB3UCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MifQ.EBs847rUL-WyoQNxAhs_cd_Sa8xy3asKZpWssXI_gOzKNPV40bQMh_Ihrcj4lH-DbICjrLpjbjqSYa99hVTdCy6e6uClDnZgFDw4XPfvXkP9Coi8oK4t2iy5YSk1P0Rsg4wHqzynY9-awhNFPSvU0_ELdMfx1QnOWTrW6RRAdua0TdKFpyaRPfPsLmN9EmdzZkTqn24JAGOWOmS62Lbrh_DRYRvi4B-eZBd8vYctirLoLHMYBgPylf5XqVPD76y3WB7z77Uby_xW7pOXEXFnKiSVuEW6FAtIPaf3x1-C3hYJdx6d3xMo6bouMJY7YBsqMQ14U4kZc8sLy8TVAbQNiw
Sec-Websocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
X-Forwarded-For: 211.204.163.221
X-Forwarded-Host: www.ttaocfcloud.org
X-Forwarded-Path: /api/v1/ws/events
X-Forwarded-Port: 8443
X-Forwarded-Proto: https
X-Real-Ip: 211.204.163.221


time="2021-08-23T08:42:57Z" level=warning msg="[write] failed to close websocket connection: use of closed network connection"
```
## Environment
plgd source : commit e019708
deployment : build on my own

**Comment by Danielius1922** [comment]
The message with given wording was added in commit e96476aa8b072f9d3e57027c471d5e60f1e19559 . Nothing should be broken, but after discussion with @jkralik attempt to close an already closed connection shouldn't be even a `warning` log so I'll change the severity to debug.

**Comment by Trishia** [comment]
@Danielius1922 

With the commit e019708, the thinks menu of web UI was broken which means noting to display on the things menu. I don't know exact reason but I witness above message in the logs of http-gateway whenever I clicked the thins menu. So I reopen this issue because of websocket message.

**Comment by Danielius1922** [comment]
Seems unlikely that adding error logs broke the UI. 0f2c187 was pushed 11 days ago and e019708 2 days ago, so that's a 9 day window for commits. The cause must be somewhere in that time period.

**Comment by Trishia** [comment]
@Danielius1922 
It was my mistake not to configure grpc-gateway about authorizationServer config which was recently added in. So I close this issue.
