### ISSUE TITLE
Configurable command timeout

### ISSUE THREAD

**Issue by ondrejtomcik** [plgd-dev/hub#364]
### What is the purpose of the feature?
`UPDATE`, `CREATE`, `DELETE` and `RETRIEVE_FROM_DEVICE` commands are registered as pending commands and will stay there forever if the device is offline. We would like to be able to configure the command time to live, so it expires at some point and won't stay as a pending one forever.

### What specific challenge does this feature solve?
Update command we send to the device shall expire if the device is offline for more than 1 minute. 

### What alternatives did I consider?
Cancel the command on our own after one minute, but there is currently no API to cancel the pending command.

**Comment by makothap** [comment]
The  design preference is option-B: Query parameter [ttl] with a number of nanoseconds the command is valid after it's accepted by the resource aggregate. The response confirming the command would return the timestamp when the command expires.

- Provide a default TTL
- Add a system level TTL configuration (if its not provided at request level)
