### ISSUE TITLE
Cancellation of pending commands

### ISSUE THREAD

**Issue by ondrejtomcik** [plgd-dev/hub#371]
### What is the purpose of the feature?
`UPDATE`, `CREATE`, `DELETE` and `RETRIEVE_FROM_DEVICE` commands are registered as pending commands and will stay there forever if the device is offline. We would like to be able to cancel these pending commands using plgd gRPC / HTTP Gateways.

### What specific challenge does this feature solve?
Command became invalid for some reason and we need a possibility to cancel it before device comes online and processes it.

### What alternatives did I consider?
Track if the device is online and only then send the command, but the problem is that if we send the command, the device can at the same time go offline.

**Comment by makothap** [comment]
- Add brief feature description and the impacted services
- Add a query API to get the list of pending commands
- Query API should provide the wildcard search based on CorrelationID; This returns the results to application (as applicable to the app)

**Comment by ondrejtomcik** [comment]
FYI @jkralik
