### ISSUE TITLE
coap gateway do not start with fatal randomly

### ISSUE THREAD

**Issue by InfiRR** [plgd-dev/hub#447]
Not reproducible all the time but on some occasions, after the start, the system fails to onboard devices and this can be seen in the log's from coap-gateway.log

{"level":"fatal","ts":1630674629.136271,"caller":"log/log.go:129","msg":"cannot load config: invalid config: yaml: unmarshal errors:\n  line 2: cannot unmarshal !!str `false` into bool","stacktrace":"github.com/plgd-dev/cloud/pkg/log.Fatalf\n\t/go/src/github.com/plgd-dev/cloud/pkg/log/log.go:129\nmain.main\n\t/go/src/github.com/plgd-dev/cloud/coap-gateway/cmd/service/main.go:15\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}

The system is started using docker-compose. PLGD bundle uses the following flags:

 FQDN: ${IP}
 LOG_DEBUG: "false"
 JETSTREAM: "true"

Generically stopping and just restarting using the same docker images solves the issue.

The full log's collected are attached
[archive.tar.gz](https://github.com/plgd-dev/cloud/files/7106156/archive.tar.gz)

**Comment by ondrejtomcik** [comment]
@InfiRR is this issue still valid?

**Comment by jkralik** [comment]
Pls reopen if the issue occurs again.
