### ISSUE TITLE
Pods not starting due to 'too many open files' error

### ISSUE THREAD

**Issue by itestoss** [plgd-dev/hub#641]
### Description
When deploying PLGD it seems if the number of pods being deployed is high enough then some will not run. For example if 20 coap gw (replicas) pods are configured to be deployed then 7 will never reach running state. 

### How can it be reproduced?
1. deploy using command:
microk8s.helm3 install am-1 -f withMock.yaml plgd/plgd-hub --create-namespace --namespace=am-1
withMock.yaml content:

```
global:
  domain: "host.domain.com"
  hubId: "d03a1bb4-0a77-428c-b78c-1c46efe6a38e"
mockoauthserver:
  enabled: true
resourcedirectory:
  log:
    debug: true
resourceaggregate:
  log:
    debug: true
httpgateway:
  log:
    debug: true
grpcgateway:
  log:
    debug: true
coapgateway:
  log:
    debug: true
  replicas: 20
  port: 5683
  service:
    type: NodePort
    nodePort: 5683
  apis:
    coap:
      tls:
        enabled: false
```

### Logs, error output, etc.

Log from a coap gw pod that does not reach running state (continuously restarting):
```
2022-01-19T16:34:13.332Z        FATAL   log/log.go:129  cannot create service: cannot create identity-store client: cannot create connection to identity-store: cannot create cert manager: too many open files
github.com/plgd-dev/hub/v2/pkg/log.Fatalf
        /go/src/github.com/plgd-dev/hub/pkg/log/log.go:129
main.main
        /go/src/github.com/plgd-dev/hub/coap-gateway/cmd/service/main.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:255

```
The pods that fail to reach running state are not always coap gw pods. Sometimes there are other pods, which fail in a similar fashion and give the same error message. What seems constant is the number of pods that do not run after PLGD installation.
The OS Kernel open file settings used are the following:

```
#ulimit -Hn
262144
#ulimit -Sn  (increased this one from 1024 to 250K but did not made any difference)
250000 
#cat /proc/sys/fs/file-max
1613280
```
I also see that the number of entries in lsof command jumps about 60K with PLGD deployed (far more than everything else in the OS)

### Environment
- microk8s v1.22.4 (snap) running on CentOS Linux release 8.5.2111
- microk8s helm3 v3.5.0
- plgd hub tag: 2.2.3
- IoTivity version: none (issue is reproducible with no IOT devices connected to PLGD)
- Deployment option: ( `helm` )

**Comment by ondrejtomcik** [comment]
@itestoss sorry for the late reply, we had other high-prio topics to resolve first.

Issue occurs because the maximum instances of [inotify](https://man7.org/linux/man-pages/man7/inotify.7.html) per user was reached. Default value of `fs.inotify.max_user_instances` is set to 128, what is a pretty low number for your usecases.

Changing this default value on your VM to e.g. 512 solves your problem. 
`sysctl -n -w fs.inotify.max_user_instances=512`
