### ISSUE TITLE
Recreated resource is not republished

### ISSUE THREAD

**Issue by jbinfn** [plgd-dev/hub#766]
A resource was created with specific attributes and values. Then it was deleted and re-created again with exact same properties as before.
It was observed that resource was not republished.

If the resource is re-created but with a different value in some attribute, it is republished.

**Comment by jkralik** [comment]
Hi @jbinfn.

Pls  could you describe your environment setup:

- hub version
- iotivity-lite - commit revision
- number of devices in the test
- debug logs from the coap-gateway

Thx

**Comment by jbinfn** [comment]
Hi,

Hub version - v2.4.5
iotivity-lite - commit revision - 80adee9 

Test details and logs sent via e-mail
